---
title: "Algorithms in ddpcr analysis"
author: "Dean Attali"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Algorithms in ddpcr analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---
  
```{r setup, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(tidy = FALSE, comment = "#>")
```

# Algorithms used to analyze ddPCR droplets

The algorithm described below consists of five main steps that are used to analyze a ddPCR plate with (FAM+)/(FAM+HEX+) clusters. Droplets in the (FAM+HEX+) cluster will be referred to as *wildtype*, and droplets in the (FAM+HEX-) cluster will be referred to as *mutant*. The final goal is to calculate the mutant frequency (*MF*) in each well by classifying all temlpate-containing droplets as wildtype or mutant.

Plates with (HEX+)/(FAM+HEX+) clusters use a very similar algorithm but HEX and FAM are swapped in every step. Plates that are neither (FAM+)/(FAM+HEX+) nor (HEX+)/(FAM+HEX+) only benefit from the first three steps of the pipeline (droplet gating is not performed). 

The initial droplet data is a list of *n* matrices, where *n* is the number of wells. Each matrix contains has two clumns and *m_i* rows, where *m_i* is the number of droplets in the *i*-th well. Each row represents a single droplet in a well and the two columns are the measured values of HEX and FAM fluorescence intensity. 

## Step 1: Identify failed wells

The first step is to identify any wells that clearly failed the ddPCR run by checking four quality control metrics.

(1) The total number of droplets in a well must exceed a specific threshold value (`params(plate, 'REMOVE_FAILURES', 'TOTAL_DROPS_T')`, default is 5000). BioRad claims that wells should have 20,000 droplets, but in practice we usually see between 12,000-17,000 droplets per well, and any well with too few droplets is considered a failure.

The other three metrics evaluate the expected droplet clusters (empty, mutant, wildtype) and their quality by fitting a two-component Gaussian mixture model to the FAM signals of all droplets. Each of the two components is defined with a mean (*center*) and a standard deviation (*sd*). In a typical well, the distribution with the lower center will capture the empty droplets, while the higher distribution models the FAM+ (or template-containing) droplets. Every well is expected to have mostly empty droplets, so (2) acceptable segregation of empty droplets from the FAM+ cluster is assessed by measuring the difference between the centers of the two distributions. (3) The droplet density within the lower (empty) population is evaluated to ensure it the fraction of droplets is above a certain threshold (`params(plate, 'REMOVE_FAILURES', 'EMPTY_LAMBDA_LOW_T')`, default is 0.3), as failure to meet this criterion indicates a lack of a defined empty cluster. (4) Similarly, the droplet density must also be below a certain fraction (`params(plate, 'REMOVE_FAILURES', 'EMPTY_LAMBDA_HIGH_T')`, default is 0.99), as having too many empty droplets is a sign that there are not enough amplifiable template in the well.

Any well that does not meet all four critera is deemd a failed run, and such wells are removed from further analysis.

## Step 2: Identify outlier droplets

While the FAM and HEX signal intensities have a lower bound of 0, there is no upper bound on the value the ddPCR reader may read. As a result, it is possible to observe a small number of droplets with abnormally large HEX or FAM values, which can be considered outlier droplets.  A common method for detecting outliers in normal distributions is to calculate the first quartile (*Q1*), third quartile (*Q3*), and interquartile range (*IQR*, defined as *Q3 - Q1*), and define any observations that fall outside the range of [_Q1 - 1.5*IQR_, _Q3 + 1.5*IQR_] as outliers.

If ddPCR data was normal and this method could be used, only the upper bound of _Q3 + 1.5*IQR_ would be used to define outliers, as there are no outliers on the lower end of the distribution because most values are close to the minimum value of 0.  However, ddPCR data is extremely skewed and non-normal, so the common outlier detection approach will not work. Instead, a small tweak can be made to make it applicable to ddPCR data. For each signal dimension (FAM and HEX) we identify the top *p* percent (*p* = `params(plate, 'REMOVE_OUTLIERS', 'TOP_PERCENT')`, default is 1%) of droplets having the highest signal value in that dimension out of droplets in the entire plate. An outlier threshold is then defined as _Q3 + k*IQR_ (*k* = `params(plate, 'REMOVE_OUTLIERS', 'TOP_PERCENT')`, default is 5) of this subset of droplets, and any droplets that have a signal value larger than this threshold are considered outliers. Essentially, this is a variation on the common outlier detection method but the outlier threshold is calculated using only a fraction of the droplets.

Any droplet in any well that has a FAM value exceeding the FAM outlier threshold or a HEX value exceeding the HEX outlier threshold is considered an outlier droplet, and removed from further analysis.

## Step 3: Identify empty droplets

Droplets with very low fluorescent signal are considered empty and are removed from any downstream analysis. These droplets do not contain any amplifiable template and make up the majority of droplets in a typical well. The removal of empty droplets is beneficial for two reasons. First, it greatly reduces the dimension of the data, which consequently allows for faster computations on the remaining droplets. Secondly, removing the major cluster of empty droplets also serves to eliminate any bias in a statistic model that would be otherwise dominated by the large number of empty droplets. While a large portion of the droplets is discarded, no useful information is lost as all the template-containing droplets are retained.

Empty droplets are identified in each well separately. First, a two-component Gaussian mixture model is fitted to the FAM signals of all droplets in a well. Only the FAM signal is used because all empty droplets emit no FAM signal while all template-containing droplets will surely emit FAM signal. Note that the same argument cannot be applied to the HEX signal because both empty droplets and mutant droplets are HEX-, so FAM can be used as a discriminant for empty dropletw while HEX cannot. The Gaussian distribution with the lower mean is assumed to be modelling the empty droplets, and it will likely have a fairly small standard deviation (*sd*) as the empty droplets are densely clustered. A FAM threshold for empty droplets is then calculated using the assumption that the FAM value of empty droplets can be roughly modeled by a normal distribution. Specifically, a threshold is defined as _mean + k*sd_ (*k* = `params(plate, 'REMOVE_EMPTY', 'CUTOFF_SD')`, default is 7) of the lower (empty) distribution. Any droplets in the well with a FAM value lower than the threshold are deemed empty.

## Step 4: Gate droplets

https://github.com/jennybc/haynes/blob/master/analysis/22_gate-using-inflection-points.R
https://github.com/jennybc/haynes/blob/master/analysis/23_inflection-points-optimize-density-bw.R
https://github.com/jennybc/haynes/blob/master/analysis/24_density-minima-instead-of-inflection-points.R

---


## classify:

After successfull identifying the "filled" droplets, the step of separating MT from WT drops was previously done using a mixture model of 2 normal distributions, but now I'm looking into doing it by looking at the inflection point on the density curve. The hardest part is figuring out what bandwidth to use for the smoothing. Using too high of a bandwidth will not find the mutant cluster, and too low will call every droplet a mutant cluster. There doesn't seem to be a single global value that can be used, even within the same dataset different bandwiths are optimal for different wells, and using too high/too low of a bandwidth doesn't identify the correct gates.


## mutant vs wildtype

We can call a well as mutant if it is statistically significantly more than
1% with a p-val < 0.01. For example, if there are 500 total drops and 7
mutant drops, then the mutant frequency is 1.4%, but is it statistically
significantly more than 1%?
P(x >= 7)
  = 1 - P(x <= 7) + P(x = 7)
  = 1 - pbinom(7, 500, .01) + dbinom(7, 500, .01)
  = 0.237
  > 0.01
  
So not statistically significantly enough, so we say it's a wildtype well.
But if there are 5000 drops and 70 mutant drops (same 1.4% frequency but
with higher absolute numbers), then
P(x >= 70) = 1 - pbinom(70, 5000, .01) + dbinom(70, 5000, .01) = 0.004
So this is indeed significant, and this well would be deemed mutant.

## reclassify:

wells without a significant mutant cluster have very few (if any) mutant
drops, so it's difficult and highly variable to identify them.  We can try
to leverage data from wells with many mutant drops to get a good idea of
where mutant drops should be found in a low mutant frequency well.  However,
this is only possible if there is enough data to learn from - ie. if there are 
less than 4 (PARAMS$RECLASSIFY_LOW_MT$MIN_WELLS_MT_CLUSTER) wells with 
high mutant frequency, then we skip this step.  
For every well with a high mutant frequency, we want to know where the
mutant cluster is relative to the wild-type cluster. To do this, 
we look at where the mutant cluster right-most (HEX) border is and
where the right-most wild-type drop is for every high mutant frequency well.
We calculate the ratio of the mutant border HEX over the largest wild-type HEX,
and call this the mutant-to-wildtype-border ratio.  In the wild-type cluster,
we decide to measure the highest HEX value of a drop instead of the actual border
because many times the right border is outside the range of the plot and is
less informative.
After calculating this ratio for all high mutant frequency wells, we
choose a single value to use as a "consensus" mutant-to-wildtype-border-ratio.
Instead of taking the mean or median, we take the the 3rd quartile
(PARAMS$RECLASSIFY_LOW_MT$BORDER_RATIO_QUANTILE) in order to be more
sensitive and not lose too many mutant drops.
After obtaining the consensus mutant-to-wildtype-border-ratio, we can
look at every low mutant frequency well, and based on the largest wild-type
HEX in each well, we can use the ratio to determine where to draw the mutant
cluster border.  In the FAM dimension, we make the FAM borders for
for the mutant cluster the same as the borders for the wild-type cluster.
With these new mutant cluster borders in place, we first reclassify all 
the previously assigned mutant drops as rain, and then assign the mutant
label to any drop that falls inside the new borders.