# This file defines constants used in the package

STATUS_UNDEFINED               <- 0L
STATUS_INIT                    <- 1L
STATUS_OUTLIERS_REMOVED        <- 2L
STATUS_FAILED_REMOVED          <- 3L
STATUS_EMPTY_REMOVED           <- 4L
STATUS_DROPLETS_CLASSIFIED     <- 5L
STATUS_DROPLETS_RECLASSIFIED   <- 6L

CLUSTER_UNDEFINED  <- 0L
CLUSTER_OUTLIER    <- 1L
CLUSTER_EMPTY      <- 2L
CLUSTER_WT         <- 3L
CLUSTER_MT         <- 4L
CLUSTER_RAIN       <- 5L

SEED <- 8

DEFAULT_PLATE_META <-
  expand.grid(LETTERS[1:8], 1:12, stringsAsFactors = FALSE) %>%
  magrittr::set_colnames(c("row", "col")) %>%
  dplyr::mutate_("well" = ~ sprintf("%s%02d", row, col),
                 "sample" = NA) %>%
  dplyr::select_("well", "sample", "row", "col")

# Each parameter has a somewhat descriptive name of what it is used for, and
# all parameters used by a single step in the pipeline are in a list together
PARAMS_OUTLIERS <- list()
PARAMS_OUTLIERS['TOP_PERCENT'] <- 1
PARAMS_OUTLIERS['CUTOFF_IQR'] <- 5
PARAMS_WELLSUCCESS <- list()
PARAMS_WELLSUCCESS['TOTAL_DROPS_T'] <- 5000
PARAMS_WELLSUCCESS['NORMAL_LAMBDA_LOW_T'] <- 0.3
PARAMS_WELLSUCCESS['NORMAL_LAMBDA_HIGH_T'] <- 0.99
PARAMS_WELLSUCCESS['NORMAL_SIGMA_T'] <- 200
PARAMS_EMPTY <- list()
PARAMS_EMPTY['CUTOFF_SD'] <- 7
PARAMS_PCR <- list()
PARAMS_PCR['DROPLET_VOLUME'] <- 0.91e-3
PARAMS_ASSIGN_CLUSTERS <- list()
PARAMS_ASSIGN_CLUSTERS['NUM_ATTEMPTS_SEGREGATE'] <- 1
PARAMS_ASSIGN_CLUSTERS['SEGREGATE_RATIO_THRESHOLD'] <- 0.75
PARAMS_ASSIGN_CLUSTERS['CLUSTERS_BORDERS_NUM_SD'] <- 3
PARAMS_ASSIGN_CLUSTERS['NO_CLUSTER_MT_BORDER_NUM_SD'] <- 10
PARAMS_ASSIGN_CLUSTERS['ADJUST_MIN'] <- 4
PARAMS_ASSIGN_CLUSTERS['ADJUST_MAX'] <- 20
PARAMS_RECLASSIFY_LOW_MT <- list()
PARAMS_RECLASSIFY_LOW_MT['MIN_WELLS_MT_CLUSTER'] <- 4
PARAMS_RECLASSIFY_LOW_MT['BORDER_RATIO_QUANTILE'] <- 0.75
DEFAULT_PARAMS <- list(
  'OUTLIERS' = PARAMS_OUTLIERS,
  'WELLSUCCESS' = PARAMS_WELLSUCCESS,
  'EMPTY' = PARAMS_EMPTY,
  'PCR' = PARAMS_PCR,
  'ASSIGN_CLUSTERS' = PARAMS_ASSIGN_CLUSTERS,
  'RECLASSIFY_LOW_MT' = PARAMS_RECLASSIFY_LOW_MT  
)