# Each parameter has a somewhat descriptive name of what it is used for, and
# all parameters used by a single step in the pipeline are in a list together
PARAMS_OUTLIERS <- list()
PARAMS_OUTLIERS['TOP_PERCENT'] <- 1
PARAMS_OUTLIERS['CUTOFF_IQR'] <- 5
PARAMS_WELLSUCCESS <- list()
PARAMS_WELLSUCCESS['TOTAL_DROPS_T'] <- 5000
PARAMS_WELLSUCCESS['NORMAL_LAMBDA_LOW_T'] <- 0.3
PARAMS_WELLSUCCESS['NORMAL_LAMBDA_HIGH_T'] <- 0.99
PARAMS_WELLSUCCESS['NORMAL_SIGMA_T'] <- 200
PARAMS_EMPTY <- list()
PARAMS_EMPTY['CUTOFF_SD'] <- 7
PARAMS_PCR <- list()
PARAMS_PCR['DROPLET_VOLUME'] <- 0.91e-3
PARAMS_ASSIGN_CLUSTERS <- list()
PARAMS_ASSIGN_CLUSTERS['NUM_ATTEMPTS_SEGREGATE'] <- 5
PARAMS_ASSIGN_CLUSTERS['SEGREGATE_RATIO_THRESHOLD'] <- 0.75
PARAMS_ASSIGN_CLUSTERS['CLUSTERS_BORDERS_NUM_SD'] <- 3
PARAMS_ASSIGN_CLUSTERS['NO_CLUSTER_MT_BORDER_NUM_SD'] <- 10
PARAMS_RECLASSIFY_LOW_MT <- list()
PARAMS_RECLASSIFY_LOW_MT['MIN_WELLS_MT_CLUSTER'] <- 4
PARAMS_RECLASSIFY_LOW_MT['BORDER_RATIO_QUANTILE'] <- 0.75
PARAMS <- list(
  'OUTLIERS' = PARAMS_OUTLIERS,
  'WELLSUCCESS' = PARAMS_WELLSUCCESS,
  'EMPTY' = PARAMS_EMPTY,
  'PCR' = PARAMS_PCR,
  'ASSIGN_CLUSTERS' = PARAMS_ASSIGN_CLUSTERS,
  'RECLASSIFY_LOW_MT' = PARAMS_RECLASSIFY_LOW_MT  
)